server:
  port: 6789

mysql:
  host: 150.109.49.131
  port: 3306

spring:
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/only?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    validationQuery: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate.ddl-auto: update


